// flow-typed signature: c77e7c718933121018c749af9da904db
// flow-typed version: <<STUB>>/cleave.js_v0.7.23/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cleave.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cleave.js' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cleave.js/react' {
    declare module.exports: any;
}
