// flow-typed signature: 4575c762df9012ec7528917c3a122f59
// flow-typed version: <<STUB>>/qrcode.react_v0.8.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode.react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode.react' {
    declare module.exports: any;
}
