// flow-typed signature: 57c08d523b075c05bf3e1cc7b0f66aea
// flow-typed version: <<STUB>>/react-select_v1.2.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
    declare module.exports: any;
}
