// flow-typed signature: fc93733eebc68db59beb69a9b838606a
// flow-typed version: <<STUB>>/react-tippy_v1.2.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tippy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tippy' {
    declare module.exports: any;
}
