// flow-typed signature: 69c4c43fc379ace04428af572fb0af1e
// flow-typed version: <<STUB>>/react-datepicker_v0.54.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datepicker' {
    declare module.exports: any;
}
