// flow-typed signature: ed3ff39266bd0bb65b7088a151e00306
// flow-typed version: <<STUB>>/react-table_v6.8.6/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-table' {
    declare module.exports: any;
}
