// flow-typed signature: 32182771ded82354fb68dc3872a0bb93
// flow-typed version: <<STUB>>/scriptjs_v2.5.8/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scriptjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scriptjs' {
    declare function $script(deps: string | string[], callback: () => mixed): void;

    declare module.exports: typeof $script;
}
